theme: jekyll-theme-slate

# Setup
title:               Social Media Research Group Hackathon 2017
tagline:             'Social Media Research Group'




github:
repo: https://github.com/SMRGHackathon2017
